on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download
        run: scripts/download.sh

      - name: Process
        run: scripts/release.sh
